// Package analysisui hosts the embedded cohort analysis SPA that gets served
// under /analysis/. The production bundle is generated by the analysis-ui/
// SvelteKit project (`make ui-build`) into server/analysisui/dist and included
// in the Go binary via //go:embed.
package analysisui
