// Command export-tags writes the possible tags per testcase as JSON and as a markdown summary.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"codeberg.org/pawal/gonemaster/tools/specifications/internal/specdata"
)

const (
	defaultJSONOut     = "docs/specifications/possible-tags-by-testcase.json"
	defaultMarkdownOut = "docs/specifications/possible-tags-by-testcase.md"
)

var sources = []string{
	"engine/test/basic/basic.go:Metadata",
	"engine/test/address/address.go:AddressMetadata",
	"engine/test/connectivity/connectivity.go:Metadata",
	"engine/test/consistency/consistency.go:Metadata",
	"engine/test/delegation/delegation.go:Metadata",
	"engine/test/dnssec/dnssec.go:Metadata",
	"engine/test/nameserver/nameserver.go:Metadata",
	"engine/test/syntax/syntax.go:Metadata",
	"engine/test/zone/zone.go:Metadata",
}

type exportPayload struct {
	GeneratedBy string                         `json:"generated_by"`
	Source      []string                       `json:"source"`
	Summary     exportSummary                  `json:"summary"`
	Modules     map[string]map[string][]string `json:"modules"`
}

type exportSummary struct {
	ModuleCount    int `json:"module_count"`
	TestcaseCount  int `json:"testcase_count"`
	UniqueTagCount int `json:"unique_tag_count"`
}

type output struct {
	path    string
	content string
}

func main() {
	jsonOut := flag.String("json-out", defaultJSONOut, "Path to write the JSON inventory")
	markdownOut := flag.String("markdown-out", defaultMarkdownOut, "Path to write the markdown summary")
	check := flag.Bool("check", false, "Verify both files are up to date instead of writing them")
	flag.Parse()

	if err := run(specdata.KnownTagsByModule(), *jsonOut, *markdownOut, *check); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(modules map[string]map[string][]string, jsonOut, markdownOut string, check bool) error {
	payload := buildPayload(modules)
	jsonContent, err := renderJSON(payload)
	if err != nil {
		return err
	}
	outputs := []output{
		{path: jsonOut, content: jsonContent},
		{path: markdownOut, content: renderMarkdown(payload)},
	}

	for _, out := range outputs {
		if check {
			existing, err := os.ReadFile(out.path)
			if err != nil {
				return fmt.Errorf("read %s: %w", out.path, err)
			}
			if string(existing) != out.content {
				return fmt.Errorf("%s is out of date; run: make spec-export-tags", out.path)
			}
			continue
		}
		if err := os.WriteFile(out.path, []byte(out.content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", out.path, err)
		}
	}
	return nil
}

func buildPayload(modules map[string]map[string][]string) exportPayload {
	testcaseCount := 0
	allTags := map[string]bool{}
	for _, testcases := range modules {
		testcaseCount += len(testcases)
		for _, tags := range testcases {
			for _, tag := range tags {
				allTags[tag] = true
			}
		}
	}

	return exportPayload{
		GeneratedBy: "go run ./tools/specifications/export-tags",
		Source:      sources,
		Summary: exportSummary{
			ModuleCount:    len(modules),
			TestcaseCount:  testcaseCount,
			UniqueTagCount: len(allTags),
		},
		Modules: modules,
	}
}

func renderJSON(payload exportPayload) (string, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	if err := enc.Encode(payload); err != nil {
		return "", fmt.Errorf("encode export payload: %w", err)
	}
	return buf.String(), nil
}

func renderMarkdown(payload exportPayload) string {
	var b strings.Builder
	b.WriteString(`# Possible Tags By Testcase

This document describes the authoritative tags-per-testcase artifact generated from
gonemaster module metadata functions.

Generated by: ` + "`make spec-export-tags`" + `. Do not edit by hand.

Primary artifact:
- ` + "`docs/specifications/possible-tags-by-testcase.json`" + `

## Scope
- Source functions:
`)
	for _, source := range payload.Source {
		fmt.Fprintf(&b, "  - `%s`\n", source)
	}

	fmt.Fprintf(&b, "\n## Summary\n- Modules: %d\n- Testcases: %d\n- Unique tags: %d\n",
		payload.Summary.ModuleCount, payload.Summary.TestcaseCount, payload.Summary.UniqueTagCount)
	b.WriteString("\nModule testcase counts:\n")
	modules := make([]string, 0, len(payload.Modules))
	for module := range payload.Modules {
		modules = append(modules, module)
	}
	slices.Sort(modules)
	for _, module := range modules {
		fmt.Fprintf(&b, "- `%s`: %d\n", module, len(payload.Modules[module]))
	}

	b.WriteString("\n## Regeneration\nRun:\n\n```sh\nmake spec-export-tags\n```\n\nGenerator source:\n- `tools/specifications/export-tags/main.go`\n")
	return b.String()
}
