package badkeys

import (
	"math/big"
)

// Precomputed constants.
var (
	bigOne   = big.NewInt(1)
	bigTwo   = big.NewInt(2)
	bigThree = big.NewInt(3)
	bigFive  = big.NewInt(5)

	// Product of all primes <= 65537, computed once at init.
	smallPrimeProduct *big.Int

	// ROCA constants.
	rocaGenerator      = big.NewInt(65537)
	rocaGeneratorOrder = newBigFromDecimal("2454106387091158800")
	rocaModulus        = newBigFromHex("924CBA6AE99DFA084537FACC54948DF0C23DA044D8CABE0EDD75BC6")
	rocaPrimePowers    = []int64{16, 81, 25, 7, 11, 13, 17, 23, 29, 37, 41, 53, 83}
)

func init() {
	smallPrimeProduct = computeSmallPrimeProduct(65537)
}

// checkFermat detects RSA keys where p and q are close together,
// making them vulnerable to Fermat factorization.
// Performs up to 100 rounds. Returns true if factorizable.
func checkFermat(n *big.Int) bool {
	if n.Cmp(bigFive) <= 0 {
		return false
	}

	a := new(big.Int).Sqrt(n)

	diff := new(big.Int)
	for i := 0; i <= 100; i++ {
		// diff = a*a - n
		diff.Mul(a, a)
		diff.Sub(diff, n)

		if diff.Sign() >= 0 && isSquare(diff) {
			return true
		}
		a.Add(a, bigOne)
	}
	return false
}

// checkPattern detects RSA moduli containing 16 or more consecutive
// identical bytes, indicating a suspicious pattern.
func checkPattern(n *big.Int) bool {
	b := n.Bytes()
	if len(b) < 16 {
		return false
	}
	count := 1
	for i := 1; i < len(b); i++ {
		if b[i] == b[i-1] {
			count++
			if count >= 16 {
				return true
			}
		} else {
			count = 1
		}
	}
	return false
}

// checkROCA detects RSA keys generated by Infineon TPMs vulnerable to
// CVE-2017-15361 (Return of Coppersmith's Attack).
func checkROCA(n *big.Int) bool {
	if n.Cmp(bigTwo) <= 0 {
		return false
	}

	// Check: n^generator_order mod modulus == 1
	result := new(big.Int).Exp(n, rocaGeneratorOrder, rocaModulus)
	if result.Cmp(bigOne) != 0 {
		return false
	}

	for _, pp := range rocaPrimePowers {
		primePower := big.NewInt(pp)
		// order_div = generator_order / prime_power
		orderDiv := new(big.Int).Div(rocaGeneratorOrder, primePower)
		// g' = generator ^ order_div mod modulus
		gDash := new(big.Int).Exp(rocaGenerator, orderDiv, rocaModulus)
		// h' = n ^ order_div mod modulus
		hDash := new(big.Int).Exp(n, orderDiv, rocaModulus)

		found := false
		gi := big.NewInt(1) // g_dash^0 = 1
		for range pp {
			if gi.Cmp(hDash) == 0 {
				found = true
				break
			}
			gi.Mul(gi, gDash)
			gi.Mod(gi, rocaModulus)
		}
		if !found {
			return false
		}
	}
	return true
}

// checkRSAInvalid detects RSA keys with invalid parameters:
// exponent e < 3 or e >= N.
func checkRSAInvalid(n, e *big.Int) bool {
	return e.Cmp(bigThree) < 0 || e.Cmp(n) >= 0
}

// checkSmallFactors detects RSA keys whose modulus shares a factor
// with the product of all primes <= 65537.
func checkSmallFactors(n *big.Int) bool {
	if n.Cmp(bigFive) <= 0 {
		return false
	}
	gcd := new(big.Int).GCD(nil, nil, smallPrimeProduct, n)
	return gcd.Cmp(bigOne) != 0
}

// checkSmallD detects RSA keys vulnerable to Wiener's continued fraction
// attack due to a small private exponent d.
// Only meaningful when e is large (> 32 bits).
func checkSmallD(n, e *big.Int) bool {
	if e.BitLen() <= 32 {
		return false
	}

	// Compute continued fraction expansion of e/n and check convergents.
	x, y := new(big.Int).Set(e), new(big.Int).Set(n)

	// Continued fraction state for convergent computation.
	n0, d0 := big.NewInt(0), big.NewInt(1)
	n1, d1 := big.NewInt(1), big.NewInt(0)
	prevN, prevD := big.NewInt(1), big.NewInt(0)

	a := new(big.Int)
	temp := new(big.Int)
	idx := 0

	for y.Sign() > 0 {
		a.Div(x, y)
		// x, y = y, x - a*y
		temp.Mul(a, y)
		x, y = y, temp.Sub(x, temp)

		// Compute rational from continued fraction: n = a*n1 + n0, d = a*d1 + d0
		nn := new(big.Int).Mul(a, n1)
		nn.Add(nn, n0)
		dd := new(big.Int).Mul(a, d1)
		dd.Add(dd, d0)

		// Compute convergent
		var k, dg *big.Int
		if idx%2 == 0 {
			k = new(big.Int).Add(nn, prevN)
			dg = new(big.Int).Add(dd, prevD)
		} else {
			k = new(big.Int).Set(nn)
			dg = new(big.Int).Set(dd)
		}
		prevN.Set(nn)
		prevD.Set(dd)

		n0.Set(n1)
		d0.Set(d1)
		n1.Set(nn)
		d1.Set(dd)
		idx++

		if k.Sign() == 0 {
			continue
		}

		// edg = e * dg
		edg := new(big.Int).Mul(e, dg)
		// phi = edg / k
		phi := new(big.Int).Div(edg, k)

		// x_val = n - phi + 1
		xVal := new(big.Int).Sub(n, phi)
		xVal.Add(xVal, bigOne)

		// Check x_val is even
		if xVal.Bit(0) != 0 {
			continue
		}

		// half = x_val / 2
		half := new(big.Int).Rsh(xVal, 1)
		// sq = half^2 - n
		sq := new(big.Int).Mul(half, half)
		sq.Sub(sq, n)

		if sq.Sign() >= 0 && isSquare(sq) {
			return true
		}
	}
	return false
}

// isSquare returns true if n is a perfect square (n >= 0).
func isSquare(n *big.Int) bool {
	if n.Sign() < 0 {
		return false
	}
	if n.Sign() == 0 {
		return true
	}
	sqrt := new(big.Int).Sqrt(n)
	sq := new(big.Int).Mul(sqrt, sqrt)
	return sq.Cmp(n) == 0
}

// computeSmallPrimeProduct returns the product of all primes <= max.
func computeSmallPrimeProduct(max int) *big.Int {
	product := big.NewInt(2)
	// Simple sieve for primes up to max.
	sieve := make([]bool, max+1)
	for i := 2; i <= max; i++ {
		if !sieve[i] {
			if i > 2 {
				product.Mul(product, big.NewInt(int64(i)))
			}
			for j := i * i; j <= max; j += i {
				sieve[j] = true
			}
		}
	}
	return product
}

func newBigFromDecimal(s string) *big.Int {
	n, ok := new(big.Int).SetString(s, 10)
	if !ok {
		panic("invalid decimal: " + s)
	}
	return n
}

func newBigFromHex(s string) *big.Int {
	n, ok := new(big.Int).SetString(s, 16)
	if !ok {
		panic("invalid hex: " + s)
	}
	return n
}
