// Command export-testcase-descriptions writes the short testcase descriptions
// to a Hugo data file so the documentation site can annotate testcase links.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"codeberg.org/pawal/gonemaster/server"
)

const defaultOut = "site/data/testcase_descriptions.toml"

const header = `# Generated by: make spec-export-testcase-descriptions
# Source: server/testcase_descriptions.go (TestcaseDescriptions)
# Maps lowercase testcase id to a short description, consumed by the children
# shortcode to annotate testcase links. Do not edit by hand - regenerate with
# the command above.
`

func main() {
	out := flag.String("out", defaultOut, "Path to write the Hugo data file")
	check := flag.Bool("check", false, "Verify the data file is up to date instead of writing it")
	flag.Parse()

	content := renderTOML(server.TestcaseDescriptions())

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read %s: %v\n", *out, err)
			os.Exit(1)
		}
		if string(existing) != content {
			fmt.Fprintf(os.Stderr, "%s is out of date; run: make spec-export-testcase-descriptions\n", *out)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		os.Exit(1)
	}
}

// renderTOML emits the descriptions as TOML, keyed by lowercase testcase id and
// sorted for deterministic output.
func renderTOML(descriptions map[string]string) string {
	lowered := make(map[string]string, len(descriptions))
	keys := make([]string, 0, len(descriptions))
	for id, desc := range descriptions {
		key := strings.ToLower(id)
		lowered[key] = desc
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString(header)
	b.WriteByte('\n')
	for _, key := range keys {
		fmt.Fprintf(&b, "%s = %s\n", strconv.Quote(key), strconv.Quote(lowered[key]))
	}
	return b.String()
}
