// Human-readable titles for gonemaster test cases. Keyed by the lowercase
// testcase identifier (e.g. "delegation01"). Kept in sync with the canonical
// titles in ui/src/i18n/en.json (tc.* keys).

const TESTCASE_TITLES: Record<string, string> = {
  address01: "Name server address must be globally routable",
  address02: "Reverse DNS entry exists for name server IP address",
  address03: "Reverse DNS entry matches name server name",
  basic01: "The domain must have a parent domain",
  basic02: "The domain must have at least one working name server",
  basic03: "The Broken but functional test",
  connectivity01: "UDP connectivity",
  connectivity02: "TCP connectivity",
  connectivity03: "AS diversity",
  connectivity04: "IP prefix diversity",
  connectivity05: "UDP answer delivery",
  consistency01: "SOA serial number consistency",
  consistency02: "SOA RNAME consistency",
  consistency03: "SOA timers consistency",
  consistency04: "Name server NS consistency",
  consistency05: "Consistency between glue and authoritative data",
  consistency06: "SOA MNAME consistency",
  delegation01: "Minimum number of name servers",
  delegation02: "Name servers must have distinct IP addresses",
  delegation03: "No truncation of referrals",
  delegation04: "Name server is authoritative",
  delegation05: "Name server must not point at CNAME alias",
  delegation06: "Existence of SOA",
  delegation07: "Parent glue name records present in child",
  dnssec01: "Legal values for the DS hash digest algorithm",
  dnssec02: "DS must match a valid DNSKEY in the child zone",
  dnssec03: "Verify NSEC3 parameters",
  dnssec04: "Check for too short or too long RRSIG lifetimes",
  dnssec05: "Check for invalid DNSKEY algorithms",
  dnssec06: "Verify DNSSEC additional processing",
  dnssec07: "DNSSEC signed zone and DS in parent for signed zone",
  dnssec08: "Valid RRSIG for DNSKEY",
  dnssec09: "RRSIG(SOA) must be valid and created by a valid DNSKEY",
  dnssec10: "Zone contains NSEC or NSEC3 records",
  dnssec11: "DS in delegation requires signed zone",
  dnssec12: "Test for DNSSEC algorithm completeness",
  dnssec13: "All DNSKEY algorithms used to sign the zone",
  dnssec14: "Check for valid RSA DNSKEY key size",
  dnssec15: "Existence of CDS and CDNSKEY",
  dnssec16: "Validate CDS",
  dnssec17: "Validate CDNSKEY",
  dnssec18: "Validate trust from DS to CDS and CDNSKEY",
  dnssec19: "Check DNSKEY records for known cryptographic weaknesses",
  dnssec20: "NSEC/NSEC3 type bitmap at zone apex matches actual RR types",
  dnssec21: "Parent zone's DS RRset is signed by a valid DNSKEY",
  dnssec22: "In-domain nameserver address records validate under the zone's chain of trust",
  nameserver01: "A name server should not be a recursor",
  nameserver02: "Test of EDNS0 support",
  nameserver03: "Test availability of zone transfer (AXFR)",
  nameserver04: "Same source address",
  nameserver05: "Behaviour against AAAA query",
  nameserver06: "NS can be resolved",
  nameserver07: "Check whether authoritative name servers return an upward referral",
  nameserver08: "Test that QNAME case is preserved in Question section",
  nameserver09: "Test that QNAME case is ignored for the query",
  nameserver10: "Behaviour against unsupported EDNS version",
  nameserver11: "Behaviour against unknown EDNS option codes",
  nameserver12: "Behaviour against unknown EDNS Z flags",
  nameserver13: "Truncated EDNS responses include OPT record",
  nameserver15: "Name server software version disclosure",
  nameserver16: "EDNS NSID option support",
  nameserver17: "DNS Cookie support",
  nameserver18: "Extended DNS Errors (EDE)",
  syntax01: "No illegal characters in the domain name",
  syntax02: "No hyphen at the start or end of the domain name",
  syntax03: "No double hyphen in position 3 and 4 of the domain name",
  syntax04: "The NS name must have a valid domain/hostname",
  syntax05: "Misuse of '@' character in the SOA RNAME field",
  syntax06: "No illegal characters in the SOA RNAME field",
  syntax07: "No illegal characters in the SOA MNAME field",
  syntax08: "MX name must have a valid hostname",
  zone01: "Fully qualified master nameserver in SOA",
  zone02: "SOA 'refresh' minimum value",
  zone03: "SOA 'retry' lower than 'refresh'",
  zone04: "SOA 'retry' at least 1 hour",
  zone05: "SOA 'expire' minimum value",
  zone06: "SOA 'minimum' maximum value",
  zone07: "SOA master is not an alias",
  zone08: "MX is not an alias",
  zone09: "MX record present",
  zone10: "No multiple SOA records",
  zone11: "SPF policy at zone apex",
  zone12: "CSYNC RR at zone apex",
  zone13: "SPF DNS lookup limit compliance",
  zone14: "ZONEMD record at zone apex",
  zone15: "CAA records at zone apex",
};

export function testcaseTitle(testcase: string | undefined | null): string | null {
  if (!testcase) return null;
  return TESTCASE_TITLES[testcase.toLowerCase()] ?? null;
}
